apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1pUQ0NBVTBDQVFBd0lERU1NQW9HQTFVRUF3d0RZbTlpTVJBd0RnWURWUVFLREFkc1pXRnlibVZ5TUlJQgpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBd3VOVHBSZytsWlNYbUJPK3JqZTV5dytPClI4NXYvNkVjUm9BWlZWMy9SemtGRGFHVDl5RUFWUjBBTlp0T2NJZ2Y3ZTRvcDByeGJsSWF1WkxBYW5wYmEya08KN0txWC9IclBhQ2JWckJqMFd3T1Nka1lrRU1zNmZsTEVlSHc0QkNtckIrYUhOLy9KaDdPT2JVL1ZkZUFBb0V6TwpGTlNOVmRLTy8zbXNBalNtcHAwRU1lZEZYQkNHR3dOK0Zuck5yaUpvU1JLVU9VNnlZdkhJS2NqaThXbGlrRHRqCmNPOVl5Qkh4M0drSUlUN2RLRHhsUmgrTll4LzMvcC83RHlEMFp4M2JDWjZpbTVqTTJnTHpxa0JYME04M2kzQzYKNzdFMUxuTzFHK0hNUGNudEpHbHpISVRoZkRIaWovV2tzQ0dyT2JxYmpnUkZTbytPNXMzekxvWmF6VURiSHdJRApBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFakpYbXl1MHhSWTI1aGV0NEZsV2xaMy9ielJGd1A5ClFqY2JQdVM1L1BPTys5QXZxb3IzcmRXSUc0cUE4eVlQRnNjZnZrSi9DNHBZbzdNMDczTUlVaFlRdENvWjhxSUgKZE1nTkp1dlFVTEtzTk10Z2RtdENHNEtjZnlPTjQ1N1lXdExLNTQ5eDFXTWVVcTNlK09xRWJEL3lpWTB6Q3pBQgpGSFdmU3RnTFhLb1FxbGJacmdlY2xzdWlzQVAxOVEvNHphTGJqcE45K3owUnFvN2txRUYwbkxpWGR6ZUtXVjJhCkxCN2duTFdlbmFqQVJ3bTdHZElQSmpVcEtMZGJKVGhaTHh0eU50QitlYkpOa2Y4eTJ3N0k1U1RVQm1nVHd6QisKWTB3VmN3aUJ6VmUrL2RLalNDWkxJVXo4bk8vbW5Nb3VDdTFxQmswNElPNlgzOTR4TnNvNElBRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
